"""
diet_model.py
─────────────
MongoDB document model for diet plans.

Diet plans are stored in the 'diet_plans' collection in MongoDB.
Each document is keyed on (user_id, pet_id) — one plan per pet per user.

Document structure
──────────────────
{
    "_id":          ObjectId,
    "user_id":      int,          # FK → SQL users.id
    "pet_id":       int,          # FK → SQL pets.id
    "pet_name":     str,
    "generated_at": datetime,
    "plan": {
        "summary":         str,
        "daily_calories":  int,
        "meals": {
            "breakfast": { "food": str, "amount": str, "notes": str | null },
            "lunch":     { "food": str, "amount": str, "notes": str | null },
            "dinner":    { "food": str, "amount": str, "notes": str | null },
            "snacks":    { "food": str, "amount": str, "notes": str | null }
        },
        "foods_to_avoid":  list[str],
        "vet_tip":         str
    }
}

Indexes (create once at startup or via MongoDB shell)
──────────────────────────────────────────────────────
    db.diet_plans.createIndex({ "user_id": 1, "pet_id": 1 }, { unique: true })
"""

from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


# ── Sub-document models ───────────────────────────────────────────────────────

class MealItemDocument(BaseModel):
    """A single meal slot (breakfast / lunch / dinner / snacks)."""
    food:   str
    amount: str
    notes:  Optional[str] = None


class MealPlanDocument(BaseModel):
    """The structured meal plan as generated by the AI and stored in MongoDB."""
    summary:         str
    daily_calories:  int
    meals:           Dict[str, MealItemDocument]   # keys: breakfast, lunch, dinner, snacks
    foods_to_avoid:  List[str]
    vet_tip:         str


# ── Top-level document ────────────────────────────────────────────────────────

class DietPlanDocument(BaseModel):
    """
    Represents one diet_plans MongoDB document.

    Usage
    -----
    # Build from raw Mongo dict
    doc = collection.find_one({"user_id": 1, "pet_id": 3})
    plan = DietPlanDocument(**doc)

    # Dump to dict for upsert (exclude _id so Mongo generates it)
    collection.update_one(
        {"user_id": plan.user_id, "pet_id": plan.pet_id},
        {"$set": plan.model_dump(exclude={"id"})},
        upsert=True,
    )
    """
    id:           Optional[str]  = Field(None, alias="_id")   # MongoDB ObjectId as str
    user_id:      int
    pet_id:       int
    pet_name:     str
    generated_at: datetime
    plan:         MealPlanDocument

    model_config = {"populate_by_name": True}
